trigger:
  - main

pool:
  name: Default

variables:
  azureWebAppName: 'flask-azure-webapp'
  azureResourceGroup: 'flask-rg'
  pythonVersion: '3.10'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    pytest tests/
  displayName: 'Run Unit Tests'

- script: |
    zip -r app.zip *
  displayName: 'Zip app files'


- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azure-flask-fp'      # 👈 Must match your service connection name exactly
    appName: '$(azureWebAppName)'            # 👈 Matches the variable you defined at top
    package: 'app.zip'
