trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureWebAppName: 'flask-azure-webapp'
  azureResourceGroup: 'flask-rg'
  pythonVersion: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    zip -r app.zip *
  displayName: 'Zip app files'


- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'Azure Subscription 1'      # 👈 Must match your service connection name exactly
    appName: '$(azureWebAppName)'            # 👈 Matches the variable you defined at top
    package: '$(System.DefaultWorkingDirectory)/app.zip'
